const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const source = fs.readFileSync(require('node:path').join(__dirname, '../app/about/lens-gesture.ts'), 'utf8');
const output = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const exported = {};
new Function('exports', output)(exported);
const g = exported.createLensGesture();
g.start(1, 100, 100);
g.end(1, 104, 103);
assert.equal(g.allowsClick(1), true, 'finger jitter remains a tap');
g.leave();
assert.equal(g.allowsClick(1), true, 'touch pointerleave after release preserves tap');
g.start(1, 100, 100);
g.move(1, 120, 100);
g.end(1, 100, 100);
assert.equal(g.allowsClick(1), false, 'drag returning to origin must not activate');
assert.equal(g.allowsClick(0), true, 'keyboard activation remains available');
g.start(2, 10, 10);
g.end(2, 10, 30);
assert.equal(g.allowsClick(1), false, 'final release position is checked');
g.start(3, 10, 10);
g.cancel();
assert.equal(g.allowsClick(1), false, 'cancelled gesture cannot activate');
g.start(4, 10, 10);
g.leave();
assert.equal(g.allowsClick(1), false, 'leaving during a press cancels');
g.start(5, 10, 10);
g.end(5, 10, 10);
assert.equal(g.allowsClick(1), true, 'next deliberate tap recovers');
console.log('Lens gesture checks passed: jitter, release, return drag, cancel, leave, keyboard, recovery.');
